### ISSUE TITLE
Vadinfo endless recursion

### ISSUE THREAD

**Issue by lprat** [volatilityfoundation/volatility3#441] opened 2021-01-29 10:57 UTC
**Describe the bug**
```
python3 /opt/volatility3/vol.py -vvv -q -f test.ram windows.vadinfo.VadInfo > /tmp/vad
Volatility 3 Framework 1.0.0
INFO     root        : Volatility plugins path: ['/opt/volatility3/volatility3/plugins', '/opt/volatility3/volatility3/framework/plugins']
INFO     root        : Volatility symbols path: ['/opt/volatility3/volatility3/symbols', '/opt/volatility3/volatility3/framework/symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadInfo.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadInfo.nt_symbols
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadInfo.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.VadInfo.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadInfo.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.VadInfo
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadInfo.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.VadInfo.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadInfo.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.VadInfo
Level 9  volatility3.framework.interfaces.configuration: TypeError - address requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - address requirements only accept int type: None
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadInfo.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadInfo.nt_symbols
DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x1aa000
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadInfo.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadInfo.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadInfo.nt_symbols
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadInfo.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadInfo.primary.memory_layer
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadInfo.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.VadInfo.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadInfo.nt_symbols
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.VadInfo
Level 9  volatility3.framework.interfaces.configuration: TypeError - address requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - address requirements only accept int type: None
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: WintelHelper
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadInfo.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadInfo.nt_symbols
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadInfo.nt_symbols
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.symbols.windows.pdbutil: Using symbol library: ntkrnlmp.pdb/6D523BCEBA7B4056879B95580644F8ED-1
DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf801e120c000
DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_EPROCESS_QUOTA_BLOCK
DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_PAGEFAULT_HISTORY
DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_JOB_ACCESS_STATE
DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_JOB_CPU_RATE_CONTROL
DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_JOB_NOTIFICATION_INFORMATION
DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT_DATA
DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_FLS_CALLBACK_INFO
DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_ASSEMBLY_STORAGE_MAP
DEBUG    volatility3.framework.symbols: Unresolved reference: nt_symbols1!_SCSI_REQUEST_BLOCK

PID	Process	Offset	Start VPN	End VPN	Tag	Protection	CommitCharge	PrivateMemory	Parent	File	File output

4	System	0xe001b9b70990	0xfa85000000	0xfa85022fff	Vad 	PAGE_READWRITE	0	0	0x0	N/A	Disabled
4	System	0xe001ba301110	0x77c60000	0x77dcefff	Vad 	PAGE_EXECUTE_WRITECOPY	7	0	0xffffe001b9b70990	\Windows\SysWOW64\ntdll.dll	Disabled
4	System	0xe001b9a1e480	0x7ffe0000	0x7ffeffff	VadS	PAGE_READONLY	2147483647	1	0xffffe001ba301110	N/A	Disabled
4	System	0xe001ba30a0f0	0x7ffad1c60000	0x7ffad1e0cfff	Vad 	PAGE_EXECUTE_WRITECOPY	10	0	0xffffe001b9b70990	\Windows\System32\ntdll.dll	Disabled
4	System	0xe001ba5dc190	0xfa85030000	0xfa85030fff	Vad 	PAGE_READWRITE	0	0	0xffffe001ba30a0f0	N/A	Disabled
.......
Traceback (most recent call last):
  File "/opt/volatility3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/opt/volatility3/volatility3/cli/__init__.py", line 589, in main
    CommandLine().run()
  File "/opt/volatility3/volatility3/cli/__init__.py", line 319, in run
    renderers[args.renderer]().render(constructed.run())
  File "/opt/volatility3/volatility3/cli/text_renderer.py", line 178, in render
    grid.populate(visitor, outfd)
  File "/opt/volatility3/volatility3/framework/renderers/__init__.py", line 211, in populate
    for (level, item) in self._generator:
  File "/opt/volatility3/volatility3/framework/plugins/windows/vadinfo.py", line 186, in _generator
    for vad in self.list_vads(proc, filter_func = filter_func):
  File "/opt/volatility3/volatility3/framework/plugins/windows/vadinfo.py", line 106, in list_vads
    for vad in proc.get_vad_root().traverse():
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 105, in traverse
    for vad_node in self.get_left_child().dereference().traverse(visited, depth + 1):
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 111, in traverse
    for vad_node in self.get_right_child().dereference().traverse(visited, depth + 1):
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 111, in traverse
    for vad_node in self.get_right_child().dereference().traverse(visited, depth + 1):
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 111, in traverse
    for vad_node in self.get_right_child().dereference().traverse(visited, depth + 1):
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 105, in traverse
    for vad_node in self.get_left_child().dereference().traverse(visited, depth + 1):
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 111, in traverse
    for vad_node in self.get_right_child().dereference().traverse(visited, depth + 1):
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 111, in traverse
    for vad_node in self.get_right_child().dereference().traverse(visited, depth + 1):
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 111, in traverse
    for vad_node in self.get_right_child().dereference().traverse(visited, depth + 1):
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 105, in traverse
    for vad_node in self.get_left_child().dereference().traverse(visited, depth + 1):
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 105, in traverse
    for vad_node in self.get_left_child().dereference().traverse(visited, depth + 1):
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 105, in traverse
    for vad_node in self.get_left_child().dereference().traverse(visited, depth + 1):
  [Previous line repeated 90 more times]
  File "/opt/volatility3/volatility3/framework/symbols/windows/extensions/__init__.py", line 71, in traverse
    raise RuntimeError("Vad tree is too deep")
RuntimeError: Vad tree is too deep
```

**Context**
Volatility Version: git current master (today)
Operating System: Docker Debian 10
Python Version: Python 3.7.3
Suspected Operating System: Win 2012 R2
Command: windows.vadinfo (same error when run malfind, VadYaraScan -> because use vadinfo, I think)

**Additional information**
I think that the origin problem is same of issue #440 (address memory not readable).
I understand that you prefere indicate error, and it's good way, but can you add option to ignore error to get partial result (rather than nothing, especially when you use the "-r json" option)?

**Comment by lprat** [comment] 2021-01-29 11:00
Sorry, I just saw your reply!
```
We have added the fail_on_errors options to TreeRenderers, so that other user interfaces can decide whether to continue accumulating results or not:

https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/renderers/__init__.py#L190

Within the official CLI we've made the decision that results after a known issue are likely questionable and as a forensics tool we need to make certain the user is aware of this. We may in the future alter how this operates, but for now this seemed the best way of ensuring that anyone using the results of the tool knew that an issue had occurred.
```
I will try to use this options. Thanks

**Comment by ikelos** [comment] 2021-01-29 11:08
No problem, we can take a look and see if the runaway vad recursion is something else, just in case if you'd like, so I'm happy for you to reopen the issue until someone more familiar with the vad code can tell us?

As to getting the JSON rendering sorted, due to the way rendering happens (so that we can output results as they occur) and the way json operates (everything in a structure needs to be there before being output), we alllow exceptions to bubble up to the top level (unless `fail_on_errors` is unset) so it's quite difficult to maintain both capabilities at once.  As I say, we may review the decision about having exceptions stop the processing so markedly, but particularly if JSON (stdout) is piped to a file, there's no way of ensuring the warning (stderr) would necessarily be seen.

**Comment by lprat** [comment] 2021-01-29 11:28
Yes, you can reopen, for verify isnt another problem.
Thanks for fast reply!.

**Comment by ikelos** [comment] 2021-09-05 10:23
@iMHLv2 I think we've done some work on the VAD stuff since this was reported, are you ok for me to close it off or should we still be looking into it?

**Comment by iMHLv2** [comment] 2021-09-15 15:10
I think we can close it unless @lprat can share a memory sample that still exhibits this problem (or at least confirm whether it is still a problem with the latest code).

**Comment by ikelos** [comment] 2021-09-15 16:07
Feel free to reopen this if you believe the issue is still present...

**Closed as completed by ikelos** 2021-09-15 16:07 UTC
