### ISSUE TITLE
QEMU: Holes in physical address space not treated properly

### ISSUE THREAD

**Issue by NiklasBeierl** [volatilityfoundation/volatility3#587] opened 2021-11-10 15:27 UTC
**Describe the bug**

*Note*: If you are coming here because vol3 fails when analyzing a `virsh dump`, consider using `virsh dump --memory-only` instead.

I was working with QEMU dumps of various sizes: 0.5, 1, 2 and 4 GB. I converted them to "raw" files using the layerwriter plugin and then ran the pslist (and other) plugin against the raw files. I encountered this error, **but only with the 4GB dumps.**.
```
Volatility was unable to read a requested page:
0x1002ff000 in layer memory_layer (Offset outside of the buffer boundaries)

        * The base memory file being incomplete (try re-acquiring if possible)
        * Memory smear during acquisition (try re-acquiring if possible)
        * An intentionally invalid page lookup (operating system protection)
        * A bug in the plugin/volatility3 (re-run with -vvv and file a bug)

No further results will be produced
```
This also happened when running against the original qemu file. So I figured it has to be a problem with the qemu translation layer rather than layerwriter.

As you can see the phyiscal address in the warning is just above 4GB. A colleague of mine then did the following:
```
> strings 4gb-snapshot.raw | grep "BIOS-e820"
Oct 21 13:28:21 ubuntu kernel: [    0.000000] BIOS-e820: [mem 0x0000000000000000-0x000000000009fbff] usable
Oct 21 13:28:21 ubuntu kernel: [    0.000000] BIOS-e820: [mem 0x000000000009fc00-0x000000000009ffff] reserved
Oct 21 13:28:21 ubuntu kernel: [    0.000000] BIOS-e820: [mem 0x00000000000f0000-0x00000000000fffff] reserved
Oct 21 13:28:21 ubuntu kernel: [    0.000000] BIOS-e820: [mem 0x0000000000100000-0x00000000bffdffff] usable
Oct 21 13:28:21 ubuntu kernel: [    0.000000] BIOS-e820: [mem 0x00000000bffe0000-0x00000000bfffffff] reserved
Oct 21 13:28:21 ubuntu kernel: [    0.000000] BIOS-e820: [mem 0x00000000feffc000-0x00000000feffffff] reserved
Oct 21 13:28:21 ubuntu kernel: [    0.000000] BIOS-e820: [mem 0x00000000fffc0000-0x00000000ffffffff] reserved
Oct 21 13:28:21 ubuntu kernel: [    0.000000] BIOS-e820: [mem 0x0000000100000000-0x000000013fffffff] usable
``` 
Then: 
```
> cp 4gb-snapshot.raw test.raw
> dd bs=268435456 if=./4gb-snapshot.raw of=test.raw seek=16 skip=12
```
Effectively "moving up" the last GB of the raw file by one GB.
And boom, it worked:
```
vol -f test.raw linux.pslist
Volatility 3 Framework 1.0.1
Progress:  100.00 Stacking attempts finished                 
PID PPID COMM

1 0 systemd
2 0 kthreadd
3 2 rcu_gp
[...]
```
Now to my limited understanding, what happens is this:
The physical address space of the vm had some addresses at 3gig reserved for "something" (IOMem?) causing the 4th gig of memory to be mapped to the 4-5 GB range, and vol doesn't catch on to that. I don't know if its a shortcoming of vol or the qemu file format. 
On the smaller dumps this problem didn't show up because the entire physical address space fitted below 3gig.
When creating "ELF" dumps from the vms, the same "hole" is still there, but vol handles it correctly:
```
readelf -a ubuntu-18.04-server-cloudimg-amd64-4096-idle
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              CORE (Core file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          0 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         4
  Size of section headers:           0 (bytes)
  Number of section headers:         0
  Section header string table index: 0

There are no sections in this file.

There are no sections to group in this file.

Program Headers:
  Type           Offset                               VirtAddr                        PhysAddr
                      FileSiz                            MemSiz                        Flags  Align
  NOTE        0x0000000000000120  0x0000000000000000   0x0000000000000000
                    0x0000000000000330  0x0000000000000330   0x0
  LOAD        0x0000000000000450  0x0000000000000000   0x0000000000000000
                    0x00000000c0000000   0x00000000c0000000   0x0
  LOAD        0x00000000c0000450   0x00000000fffc0000      0x00000000fffc0000
                    0x0000000000040000   0x0000000000040000  0x0
  LOAD        0x00000000c0040450   0x0000000100000000  0x0000000100000000
                   0x0000000040000000   0x0000000040000000  0x0

There is no dynamic section in this file.

There are no relocations in this file.

The decoding of unwind sections for machine type Advanced Micro Devices X86-64 is not currently supported.

Dynamic symbol information is not available for displaying symbols.

No version information found in this file.
[...]
```  
**Context**
Volatility Version:  Volatility 3 Framework 1.0.1
Operating System:  Linux
Python Version:  Python 3.9.2
Suspected Operating System:  Linux
Command:  vol -f /snapshot/qemu/or/raw some_plugin

**To Reproduce**

Good question, I don't know how to get a snapshot with the same holes in the physical address space. I think I could make a transfer happen if desired.

**Expected behavior**
Correctly translating the qemu file.

**Comment by ikelos** [comment] 2021-11-10 21:36
Thanks, I'm not sure what would be causing that, but if you could create an image we could look at, that would help speed up finding the issue a great deal...

**Comment by cstation** [comment] 2021-12-29 13:34
I'm encountering the same issue as well. It can easily and reliably be reconstructed by creating a VM in QEMU with ≥4096 MB RAM and dumping it with `virsh dump`. Maybe it is related to this 'PCI-hole'? https://github.com/juergh/lqs2mem.py/blob/master/lqs2mem.py#L218 and https://qemu.readthedocs.io/en/latest/devel/memory.html

**Comment by ikelos** [comment] 2021-12-30 20:06
Just wanted to check whether this issue is distinct from the fixes that #605 put in place, or if that PR resolved this too?

**Comment by cstation** [comment] 2021-12-31 01:46
It's different, unfortunately ;)

**Comment by ikelos** [comment] 2021-12-31 01:48
Awww, ok.  I'll try to look into it soon then (I was hoping I could get two things fixed with one pull request)...  5;P  Thanks for letting me know!

**Comment by ikelos** [comment] 2022-01-07 01:03
Ok, I'm getting really confused here, the output from `python vol.py -vvvvv -f qemu-6gb.dmp layerwriter --layers memory_layer` matches exactly the output in `pc.ram` from `python analyze-migration.py -f qemu-6gb.dmp -x`, which means if we're doing something wrong, then the official qemu scripts are too.

Please could someone try both of these to make sure that they a) come out the same for them and b) both don't analyze properly, but that copying the last chunk further up works fine?  Also, if someone would be able to produce an image that doesn't work, and a modified version of the same image that does, we might have a better chance of figuring out what's going wrong (and what the modification fixes)...

**Comment by cstation** [comment] 2022-01-07 08:30
I can confirm that. What helped me for doing the analysis is performing both `virsh dump` and `virsh dump --memory-only` directly after each other for the same VM and try to find how these differ.

Having two images (one QEVM and one ELF64), I ran `layerwriter` on both of them. After that, I ran for both files `xxd -a {elf64|qevm} | grep -E '^\*' -C2 > holes_{elf64|qevm}`, which gave me an overview of the location of the holes (blobs of zero-bytes) in the file. Diffing these files (`diff -y  --suppress-common-lines holes_elf64 holes_qevm`) shows a larger gap in the ELF64.

**Comment by NiklasBeierl** [comment] 2022-01-07 09:15
Heyya, sorry for disappearing.

> Thanks, I'm not sure what would be causing that, but if you could create an image we could look at, that would help speed up finding the issue a great deal...

You are talking about a memory images (snapshots)?

Or VM images to throw onto qemu? In that case: I used an [ubuntu cloud image](http://cloud-images.ubuntu.com/releases/21.10/release/).

**Comment by ikelos** [comment] 2022-01-07 10:02
@cstation so, to confirm, you're saying that we produce the same output as the `pc.ram` produced by qemu's python script?

@NiklasBeierl yep, we're interested in the memory file (not the full vm disk image), which should start QEVM...

**Comment by cstation** [comment] 2022-01-07 10:13
@ikelos: Yes

**Comment by NiklasBeierl** [comment] 2022-01-07 11:02
Here you go: 
https://drive.google.com/drive/folders/1jCvgAfDNWdfqrqftVIuTBT-TyFyA8wH2?usp=sharing

Probably only the `-4096-` (4GB) ones are interesting, but I figured the others wont hurt.
If you need more samples, let me know.

**Comment by ikelos** [comment] 2022-01-09 21:34
@NiklasBeierl Thanks for those.  I've confirmed that the qemu analyze-migration script produces the same memory file as the `layerwriter` plugin for both 4096 images.  If you could confirm that they don't work normally, but do work when you duplicate the end further down, then this could be something we could take upstream...

I have been able to recreate an image that doesn't generate the same output as the qemu script, but I'm still investigating that one...

**Comment by ikelos** [comment] 2022-01-09 22:00
Hmmm, scratch that, my sample produces the same output as analyze-migration, so I'm still stumped as to what's up at the moment.  I'll check those 4096 images again and see if I can find something...

**Comment by cstation** [comment] 2022-03-22 20:56
@ikelos, were you able to make any progress with this issue? Is there anything we could do to help you?

**Comment by ikelos** [comment] 2022-03-22 22:49
I haven't made any progress.  I'm afraid I need two copies of the same image, one that works and one that doesn't, due only to having shifted a chunk of the memory.  I still haven't found this to produce anything different than the official python tool provided by qemu, so until we have a reproducible sample both working and none-working differing only in the gap then it's really hard to know whether there really is a problem that needs fixing.  Sorry, I understand it's a bit frustrating to have such a difficult to pin down problem, but I want to know exactly why the fix works, instead of just shifting stuff by a certain amount and suddenly it works...  5:S

**Comment by cstation** [comment] 2022-03-24 12:04
One option to create such copies is to take the `ubuntu-21.10-server-cloudimg-amd64-4096-idle` image provided by @NiklasBeierl and run the `layerwriter`-plugin twice: once using the unpatched code and once using my patch as provided in #613. The unpatched code will produce the same output as QEMU's `analyze-migration.py`, which is around 4GB. The patched code will produce an ouput of approx 5GB. Running `linux.pslist` will fail on the unpatched/analyze-migration images, but succeed on the 5GB image produced by the patched code.

I did this and uploaded the results to [ufile.io/x9lasfmf](https://ufile.io/x9lasfmf) (expires around April 23rd, 2022):
```
20bbdf532ddbc07e284049d428099c10 ubuntu-21.10-server-cloudimg-amd64-4096-idle_layerwriter_fixed_qemu_code.raw
dab46408eebdb20ad5880cf97f5c84e1 ubuntu-21.10-server-cloudimg-amd64-4096-idle_layerwriter_original_qemu_code_or_qemu_analyze-migration.raw
5785782f4f30d6225ba384d86aa24df3 Ubuntu21.10_5.13.0-19.json.xz
```
Another option is to create a QEMU-VM with >4096 MB of RAM, install Linux and create a suspend-to-disk image using `virsh-dump`. Then, you could again run `layerwriter` using the patched and original code, and compare the results. For comparison, you could also create a working(!) ELF64-image using `virsh-dump --memory-only`, but since this creates a new snapshot, the images will in the end likely differ (slightly).

This means that `analyze-migration.py` produces wrong output for images >4096 MB. This is because the script simply does not handle the gap that occurs around 4GB, which [lqs2mem](https://github.com/juergh/lqs2mem.py/blob/master/lqs2mem.py#L218) for example does. I wonder how 'official' this script is, it looks to me like some helper script for debugging purposes. Probably it has never been tested on images >4096 MB, which could easily be the case, since this issue has not been noted earlier for Volatility as well.

That still leaves the question why those gaps exist, where they reside in memory etc. The best answers for that can probably be found in the source code of qemu, where ~~the magic happens~~ this headache is caused. [Searching for `4g`](https://github.com/qemu/qemu/search?q=4g&type=code) (you should get 53 hits, if not, keep refreshing) provides some clues (e.g. [this](https://github.com/qemu/qemu/blob/d70075373af51b6aa1d637962c962120e201fc98/hw/i386/pc_q35.c#L142)), which I used as a starting point to build this table (as included in #613):
```
# See https://qemu.readthedocs.io/en/latest/devel/memory.html for more info
#
# At least the following values could occur for devices using > 3-4 GB RAM:
# +--------------------------------+--------------------------------+------------+-------------+
# | Architecture                   | Reference Code                 | Hole Start | Hole End    |
# +--------------------------------+--------------------------------+------------+-------------+
# | PC i440FX + PIIX "New Default" | qemu/hw/i386/pc_piix.c:98      | 0xc0000000 | 0x100000000 |
# | PC i440FX + PIIX "Old Default" | qemu/hw/i386/pc_piix.c:98      | 0xe0000000 | 0x100000000 |
# | PC Q35 + ICH9                  | qemu/hw/i386/pc_q35.c:141      | 0x80000000 | 0x100000000 |
# | MicroVM                        | qemu/hw/i386/microvm.c:291     | 0xc0000000 | 0x100000000 |
# | Xen                            | qemu/hw/i386/xen/xen-hvm.c:248 | 0xf0000000 | 0x100000000 |
# +--------------------------------+--------------------------------+------------+-------------+
```
The 'Reference Code'-columns contains the lines in the qemu source code (at the time of rolling the patch) which are related to the locations and sizes of the holes. I was able to verify that for PC i440FX and Q35, these holes occur at the denoted locations and successfully tested the patch in #613 on these architectures.

Given this, I am sure about the gaps and the fact that this problem can be solved by shifting up a part of the memory. However, although I have been (too) deep into this rabbit hole, I was not able to find a more elegant method for determining the location of the hole for an image than the solution as provided in #613.

**Comment by ikelos** [comment] 2022-03-24 23:12
Ok, thanks, that's great work!  I'll take a look at the image you made and see if I can accurately pinpoint why they read inaccurately.  If the official `analyze-migration.py` is inaccurate, it would be really helpful if you could file a bug upstream with qemu and see what they say, and find out if they have an accurate means to determine the gap other than simply having a hardcoded list of all the locations...

**Comment by ikelos** [comment] 2022-03-24 23:32
Interesting, the DTB is detected in the moved segment (`0xeac10000` for the original one and `0x12ac10000` for the fixed one).  That caused the ASLR values to be off as well:

Original: `Linux ASLR shift values determined: physical e7e00000 virtual 1fe00000`
Fixed: `Linux ASLR shift values determined: physical 127e00000 virtual 1fe00000`

I need to dig further, but at least we've got a clear example, thanks.  It would be really good to get an official view from qemu, but I'm more convinced this is an actual issue now.

**Closed as completed** 2022-05-23 19:35 UTC
