### ISSUE TITLE
Replacement of linux_procdump command

### ISSUE THREAD

**Issue by saneehaAmir** [volatilityfoundation/volatility3#847] opened 2022-10-06 16:22 UTC
Hey,

We have been using linux_procdump command for dumping the executable of a process. It is not available in volatility3. Please tell the replacement for this plugin.

I will be grateful
Thanks

**Comment by digitalisx** [comment] 2022-10-07 16:21
Duplicate of #764 #830

**Closed as completed** 2023-09-03 20:59 UTC
Labels: enhancement, plugin-request
