### ISSUE TITLE
yara dependencies

### ISSUE THREAD

**Issue by Mitch-sleuthkit** [volatilityfoundation/volatility3#439] opened 2021-01-28 19:27 UTC
Hi ! what am I missing ? :) On Ubuntu 18.04.3 LTS  - I installed Volatility3 from cloning GITHUB, installed the symbols for mac, windows and linux (in the plugins path shown below), PEFile (i assume this installed correctly as the related missing dependancies disappeared) and Yara Python (pip install did not seem to work for Yara, but compiling the source did reduce other missing yara issues except the ones below) 

Thanks for any assistance !

Volatility 3 Framework 1.0.0
INFO     root        : Volatility plugins path: ['/home/zaphod/volatility3/volatility3/plugins', '/home/zaphod/volatility3/volatility3/framework/plugins']
INFO     root        : Volatility symbols path: ['/home/zaphod/volatility3/volatility3/symbols', '/home/zaphod/volatility3/volatility3/framework/symbols']
INFO     volatility3.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: No module named 'yara'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.yarascan based on file: yarascan
INFO     volatility3.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: No module named 'yara'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.vadyarascan based on file: windows/vadyarascan
INFO     volatility3.plugins.windows.verinfo: Python pefile module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: No module named 'pefile'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.verinfo based on file: windows/verinfo
INFO     volatility3.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: No module named 'yara'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.svcscan based on file: windows/svcscan
INFO     volatility3.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: No module named 'yara'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.callbacks based on file: windows/callbacks
INFO     root        : The following plugins could not be loaded (use -vv to see why): volatility3.plugins.windows.callbacks, volatility3.plugins.windows.svcscan, volatility3.plugins.windows.vadyarascan, volatility3.plugins.windows.verinfo, volatility3.plugins.yarascan

**Comment by ikelos** [comment] 2021-01-28 19:57
Hiya, so several of those depend on the others, so it's predominantly the yarascan/vadyarascan plugins that aren't working.  I think pypi calls the package yara-python, but if that isn't installing properly then you should be able to compile it and install it yourself.  It needs to be yara(-python) >= 3.8.0 and you should be able to `import yara` from the python that you run volatility from once it's installed, otherwise those plugins will fail to load.  I'm not sure that you can get more logging output yet because importing the plugins happens pretty early, but you can see if `-vvvvvvv` offers any more information (that's as high as the logging levels go) too...

**Comment by iMHLv2** [comment] 2021-09-15 15:19
@Mitch-sleuthkit Did you figure this out? @ikelos We can probably close this ticket - it isn't a problem with Volatility, its more of a generic issue installing pefile and yara-python.

> PEFile (i assume this installed correctly as the related missing dependancies disappeared)

Hmm, I still see the `No module named 'pefile'` messages in the pasted output above...

> pip install did not seem to work for Yara

As @ikelos mentioned, `yara` is a command line tool, whereas `yara-python` is a python module. You can't install the `yara` command line tool through pip, since pip is only for python modules. It needs to be `pip install yara-python>=3.8.0`. 

> but compiling the source did reduce other missing yara issues except the ones below

The exact commands used to compile from source would be useful here...clearly the install didn't work, but we don't have enough information to advise on what might have gone wrong. As a side note, since this is an issue installing yara-python, it might be more appropriate to post to the [yara-python issue tracker](https://github.com/VirusTotal/yara-python/issues).

**Comment by ikelos** [comment] 2021-09-15 16:06
Feel free to reopen this if you feel the issue is still present...  5:)

**Closed as completed** 2021-09-15 16:06 UTC
Labels: question

**Comment by Mitch-sleuthkit** [comment] 2021-09-15 20:06
Sorry for not replying back! You are right, it is not a Vol issue. BR, Mitch
