### ISSUE TITLE
Plugin without requirements does not run automagic

### ISSUE THREAD

**Issue by zer0matt** [volatilityfoundation/volatility3#1383] opened 2024-12-05 22:27 UTC
Hi, whenever I try to run my own plugin it always shows the same output, no matter what memory dump I input to it.
While the core plugins start their process to run from 0 to 100%, my plugin directly skips and goes to print the same output every single time.
I'm running with the option --cache-path "path/to/my_cache"
Nothing changes if I delete the my_cache directory

Any suggestions?

Thanks

**Comment by ikelos** [comment] 2024-12-06 00:29
We'd really need to see you code but most plugins follow a pattern of a generator that generates results and then returns them as a TreeGrid.  There's no caching of results anywhere within the codebase, caching is only done on things like symbol tables and other data that's likely to be reused between runs.  Your best place to get help is likely to be [slack](https://www.volatilityfoundation.org/slack) because question and replies on a ticket take a lot of time and tend to become unreadable after  awhile.  Try asking your question in #vol3-dev and see if you can't get some more direct support...

**Comment by zer0matt** [comment] 2024-12-06 08:53
The same plugin code was running fine with a previous version of volatility3 and it respects the "standards" of the vol plugins since I wrote it by reading the docs and inspiring by other plugins, it's correctly returning a TreeGrid which generates an output and all essential methods like run() and _generator() have been wrote

**Comment by ikelos** [comment] 2024-12-06 08:58
Then I'm not sure how to help?  The core plugins get which automagic they run decided on by their plugin name (the first part is the OS, so linux, windows or mac).  All automagic should run for any other plugin name (just like layerwriter and banners, etc).  If you're getting no automagic running at all, consider running it with `-vvvvvvv` as the first flag and it should walk you through all the automagic steps it's taking.  It might also flag up if an exception is causing something in the automagic to be skipped without telling you.  Again, sharing the code or the output with at least `-vvv` is the only way we'll be able to help you diagnose what your problem is...

**Comment by zer0matt** [comment] 2024-12-06 09:07
The source code you can find it [here](https://privatebin.net/?7577680e40a31357#9KYSgaoPV1LZvaYKd66BxN1AHmoTN4SNHw16NtHbMmRZ)
Password: ****

**Comment by ikelos** [comment] 2024-12-06 09:16
Since you have no requirements, there's nothing for the automagic to do.  All requirements (none) are already met, so nothing runs and your plugin's config will be empty.  The plugin doesn't appear to make use of anything volatility related?  All the calls are to external modules that read the local registry from what I can see?  You should uncomment the kernel requirement to actually get the memory image loaded and identified and a kernel module to work with.  You should then use the registry layer and read registry keys using the registry modules (see https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/framework/plugins/windows/registry/userassist.py as an example of how to read registry keys).

**Comment by zer0matt** [comment] 2024-12-06 09:34
I uncommented the kernel line code and the get_requirements() function.
Regarding the reading of the registry keys value, should I get userassist as requirement and use it to read the keys? Or should I just re-use the modules and functions defined in userassist?

**Comment by ikelos** [comment] 2024-12-06 09:46
I just meant look at how `userassist` reads registry keys as an example.  You can also look at `printkey`.  They all use `hivelist` to locate a registry hive and then read keys using `hive.get_key`.  The point is that `winreg` will read from the local windows system, rather than using volatility to read from the memory image...

**Comment by zer0matt** [comment] 2024-12-06 09:50
That's probably why my output is always the same...how silly of me
Thanks for the support I'll try to make it works using the hivelist and hive.get_key!

**Comment by zer0matt** [comment] 2024-12-06 10:15
Sorry to ask here again...whenever I try to import and use the RegistryHive module I get the following error:

> AttributeError: module 'volatility3.plugins.windows.pslist' has no attribute 'PsList'. Did you mean: 'List'?

**Comment by ikelos** [comment] 2024-12-06 10:51
I'm really not sure what's causing that I'm afraid.  You can likely get better immediate support from our [slack channel](www.volatilityfoundation.org/slack).  Since we've diagnosed the original issue you were experiencing and it's not a bug, I'm going to close this ticket off.  Please feel free to open a new ticket if there's a specific problem with the framework.

**Closed as completed by ikelos** 2024-12-06 10:51 UTC
Labels: question
