### ISSUE TITLE
Investgating hiberfil.sys files

### ISSUE THREAD

**Issue by R0b0t7** [volatilityfoundation/volatility3#807] opened 2022-08-08 14:00 UTC
Hello!
Is there anyway to use volatility 3 inorder to investigate hiberfil.sys directly? OR is there any specific tool that we can convert hiberfil.sys that way that we can parse it using voltality 3?
I've been reading about Hiber2Bin but cannot find anyway to actually download it, while using the imagecopy in Voltality 2 does work but doesn't work - it copies into different extention but when trying to parse with voltality I'm stuck with an error.
Really looking into parsing hiberfil.sys into Vol3 - Cheers :)

**Comment by mdenzel** [comment] 2023-02-12 17:08
Considering newer versions of Windows especially: they are not supported by volatility2 any more/yet and volatility3 seems to not support hiberfil.sys.

**Comment by ikelos** [comment] 2023-02-19 10:33
This looks like it might be a duplicate of #692.  I'll prod the guys and see if they've got any spare cycles to investigate.  I think the hiberfiles tend to get wiped out on running systems and so were less valuable, but I'll see what the state of things are.  Meanwhile, I'll close this off, please follow along at #692.

**Closed as completed by ikelos** 2023-02-19 10:33 UTC
