### ISSUE TITLE
Games processes in Volatility

### ISSUE THREAD

**Issue by RubaAlsmadi** [volatilityfoundation/volatility3#1135] opened 2024-04-23 23:03 UTC
Hello there, 

First, I would like to thank you for your swift replies and immediate help with our project. 

Now I  have the memory dump for the seam deck. I acquired it while playing the War Thunder game. I'm using Volatility 3 to analyze it. 
**After prompting the pslist command**

 `python /home/deck/Desktop/volatility3/vol.py  -f /root/dump3.mem  linux.pslist.PsList`

**I got the following processes:**
 

`- OFFSET (V)      PID     TID     PPID    COMM    File output
- 
- 0x904fc0272080  1       1       0       systemd Disabled
- 0x904fc0274100  2       2       0       kthreadd        Disabled
- 0x904fc0270000  3       3       2       rcu_gp  Disabled
- 0x904fc0308000  4       4       2       rcu_par_gp      Disabled
- 0x904fc030a080  5       5       2       slub_flushwq    Disabled
- 0x904fc030c100  6       6       2       netns   Disabled
- 0x904fc0310000  8       8       2       kworker/0:0H    Disabled
- 0x904fc0394100  10      10      2       mm_percpu_wq    Disabled
- 0x904fc0392080  12      12      2       rcu_tasks_kthre Disabled
- 0x904fc0398000  13      13      2       rcu_tasks_rude_ Disabled
- 0x904fc039a080  14      14      2       rcu_tasks_trace Disabled
- 0x904fc039c100  15      15      2       ksoftirqd/0     Disabled
- 0x904fc03a4100  16      16      2       rcu_preempt     Disabled
- 0x904fc03a0000  17      17      2       rcub/0  Disabled
- 0x904fc03a2080  18      18      2       migration/0     Disabled
- 0x904fc03b2080  19      19      2       idle_inject/0   Disabled
- 0x904fc083c100  21      21      2       cpuhp/0 Disabled
- 0x904fc0880000  22      22      2       cpuhp/1 Disabled
- 0x904fc0882080  23      23      2       idle_inject/1   Disabled
- 0x904fc0884100  24      24      2       migration/1     Disabled
- 0x904fc0888000  25      25      2       ksoftirqd/1     Disabled
- 0x904fc088c100  27      27      2       kworker/1:0H    Disabled
- 0x904fc0890000  28      28      2       cpuhp/2 Disabled
- 0x904fc0892080  29      29      2       idle_inject/2   Disabled
- 0x904fc0894100  30      30      2       migration/2     Disabled
- 0x904fc089a080  31      31      2       ksoftirqd/2     Disabled
- 0x904fc0898000  33      33      2       kworker/2:0H    Disabled
- 0x904fc08ac100  34      34      2       cpuhp/3 Disabled
- 0x904fc08a8000  35      35      2       idle_inject/3   Disabled
- 0x904fc08aa080  36      36      2       migration/3     Disabled
- 0x904fc08b4100  37      37      2       ksoftirqd/3     Disabled
- 0x904fc08b2080  39      39      2       kworker/3:0H    Disabled
- 0x904fc09e0000  40      40      2       cpuhp/4 Disabled
- 0x904fc09e2080  41      41      2       idle_inject/4   Disabled
- 0x904fc09e4100  42      42      2       migration/4     Disabled
- 0x904fc09f2080  43      43      2       ksoftirqd/4     Disabled
- 0x904fc09f0000  45      45      2       kworker/4:0H    Disabled
- 0x904fc09f8000  46      46      2       cpuhp/5 Disabled
- 0x904fc09fa080  47      47      2       idle_inject/5   Disabled
- 0x904fc09fc100  48      48      2       migration/5     Disabled
- 0x904fc0a0c100  49      49      2       ksoftirqd/5     Disabled
- 0x904fc0a0a080  51      51      2       kworker/5:0H    Disabled
- 0x904fc0a12080  52      52      2       cpuhp/6 Disabled
- 0x904fc0a14100  53      53      2       idle_inject/6   Disabled
- 0x904fc0a10000  54      54      2       migration/6     Disabled
- 0x904fc0acc100  55      55      2       ksoftirqd/6     Disabled
- 0x904fc0aca080  57      57      2       kworker/6:0H    Disabled
- 0x904fc0ad4100  58      58      2       cpuhp/7 Disabled
- 0x904fc0ad0000  59      59      2       idle_inject/7   Disabled
- 0x904fc0ad2080  60      60      2       migration/7     Disabled
- 0x904fc0ad8000  61      61      2       ksoftirqd/7     Disabled
- 0x904fc0adc100  63      63      2       kworker/7:0H    Disabled
- 0x904fc090c100  64      64      2       kdevtmpfs       Disabled
- 0x904fc0908000  65      65      2       inet_frag_wq    Disabled
- 0x904fc1458000  67      67      2       khungtaskd      Disabled
- 0x904fc145a080  68      68      2       oom_reaper      Disabled
- 0x904fc1462080  70      70      2       writeback       Disabled
- 0x904fc0cd0000  71      71      2       kcompactd0      Disabled
- 0x904fc0cd2080  72      72      2       ksmd    Disabled
- 0x904fc0cd4100  73      73      2       khugepaged      Disabled
- 0x904fc0cda080  74      74      2       kintegrityd     Disabled
- 0x904fc0cdc100  75      75      2       kblockd Disabled
- 0x904fc0cd8000  76      76      2       blkcg_punt_bio  Disabled
- 0x904fc14f2080  77      77      2       ata_sff Disabled
- 0x904fc14f4100  78      78      2       edac-poller     Disabled
- 0x904fc14f0000  79      79      2       devfreq_wq      Disabled
- 0x904fc1720000  80      80      2       watchdogd       Disabled
- 0x904fc1724100  82      82      2       kworker/3:1H    Disabled
- 0x904fc1744100  83      83      2       kswapd0 Disabled
- 0x904fc1754100  89      89      2       kthrotld        Disabled
- 0x904fc2d8c100  95      95      2       irq/25-aerdrv   Disabled
- 0x904fc2d88000  96      96      2       irq/25-pcie-dpc Disabled
- 0x904fc2d94100  97      97      2       irq/26-aerdrv   Disabled
- 0x904fc2d90000  98      98      2       irq/26-pcie-dpc Disabled
- 0x904fc2d92080  99      99      2       irq/27-aerdrv   Disabled
- 0x904fc2d9a080  100     100     2       irq/27-pcie-dpc Disabled
- 0x904fc2daa080  106     106     2       acpi_thermal_pm Disabled
- 0x904fc2dac100  107     107     2       mld     Disabled
- 0x904fc2da8000  108     108     2       ipv6_addrconf   Disabled
- 0x904fc4c5a080  113     113     2       kstrp   Disabled
- 0x904fc4c78000  117     117     2       zswap1  Disabled
- 0x904fc4c7a080  118     118     2       zswap1  Disabled
- 0x904fc4c7c100  119     119     2       zswap-shrink    Disabled
- 0x904fc5860000  159     159     2       charger_manager Disabled
- 0x904fc5862080  176     176     2       kworker/6:1H    Disabled
- 0x904fc5864100  189     189     2       kworker/5:1H    Disabled
- 0x904fc61c4100  191     191     2       kworker/1:1H    Disabled
- 0x904fc61c0000  193     193     2       kworker/0:1H    Disabled
- 0x904fc61c2080  196     196     2       kworker/4:1H    Disabled
- 0x904fc61c8000  197     197     2       kworker/7:1H    Disabled
- 0x904fc1750000  198     198     2       kworker/2:1H    Disabled
- 0x904fc61ca080  200     200     2       spi0    Disabled
- 0x904fc0b24100  202     202     2       nvme-wq Disabled
- 0x904fc0b22080  203     203     2       nvme-reset-wq   Disabled
- 0x904fc2e90000  204     204     2       nvme-delete-wq  Disabled
- 0x904fc4c0c100  209     209     2       sdhci   Disabled
- 0x904fc6924100  282     282     2       btrfs-worker    Disabled
- 0x904fc6922080  283     283     2       btrfs-worker-hi Disabled
- 0x904fc6920000  284     284     2       btrfs-delalloc  Disabled
- 0x904fc0b20000  285     285     2       btrfs-flush_del Disabled
- 0x904fcb97a080  286     286     2       btrfs-cache     Disabled
- 0x904fcb97c100  287     287     2       btrfs-fixup     Disabled
- 0x904fcb978000  288     288     2       btrfs-endio     Disabled
- 0x904fcbd88000  289     289     2       btrfs-endio-met Disabled
- 0x904fcbd8a080  290     290     2       btrfs-endio-rai Disabled
- 0x904fcbd8c100  291     291     2       btrfs-rmw       Disabled
- 0x904fcc250000  292     292     2       btrfs-endio-wri Disabled
- 0x904fcc252080  293     293     2       btrfs-compresse Disabled
- 0x904fcc254100  294     294     2       btrfs-freespace Disabled
- 0x904fcc25a080  295     295     2       btrfs-delayed-m Disabled
- 0x904fcc25c100  296     296     2       btrfs-qgroup-re Disabled
- 0x904fcc258000  297     297     2       btrfs-cleaner   Disabled
- 0x904fcb3c8000  298     298     2       btrfs-transacti Disabled
- 0x904fcb3cc100  308     308     2       jbd2/nvme0n1p7- Disabled
- 0x904fcb3d0000  309     309     2       ext4-rsv-conver Disabled
- 0x904fc68ec100  368     368     1       systemd-journal Disabled
- 0x904fc61ec100  383     383     1       systemd-udevd   Disabled
- 0x904fc6130000  428     428     2       irq/73-FTS3528: Disabled
- 0x904fc68ea080  441     441     2       jbd2/nvme0n1p8- Disabled
- 0x904fc1742080  442     442     2       ext4-rsv-conver Disabled
- 0x904fcb1ac100  470     470     2       cryptd  Disabled
- 0x904fcfff2080  474     474     2       cfg80211        Disabled
- 0x904fcb770000  517     517     2       irq/75-AudioDSP Disabled
- 0x904fcbcfa080  531     531     2       ath11k_wq       Disabled
- 0x904fcbcf8000  532     532     2       ath11k_aux_wq   Disabled
- 0x904fe3a04100  533     533     2       irq/77-bhi      Disabled
- 0x904fd8408000  543     543     1       systemd-resolve Disabled
- 0x904fd1fd0000  544     544     2       amdgpu-reset-de Disabled
- 0x904fd840a080  545     545     1       systemd-timesyn Disabled
- 0x904fcb9c8000  548     548     2       irq/74-nau8821  Disabled
- 0x904fd8404100  554     554     1       bluetoothd      Disabled
- 0x904fcb9cc100  555     555     2       amdgpu_dm_hpd_r Disabled
- 0x904fc6134100  556     556     2       amdgpu_dm_hpd_r Disabled
- 0x904fcc242080  557     557     2       dm_vblank_contr Disabled
- 0x904fd8402080  558     558     1       dbus-daemon     Disabled
- 0x904fd8400000  559     559     1       ds-inhibit      Disabled
- 0x904fd101c100  560     560     1       python3 Disabled
- 0x904fc69ac100  563     563     1       fancontrol.py   Disabled
- 0x904fc69aa080  566     566     1       socat   Disabled
- 0x904fc1740000  576     576     1       python  Disabled
- 0x904fcb568000  578     578     1       systemd-logind  Disabled
- 0x904fe3a74100  581     581     1       vpower  Disabled
- 0x904fe2678000  676     676     1       firewalld       Disabled
- 0x904fe57ec100  706     706     2       card0-crtc0     Disabled
- 0x904fe57e8000  707     707     2       card0-crtc1     Disabled
- 0x904fe3a94100  708     708     2       card0-crtc2     Disabled
- 0x904fe3a90000  709     709     2       card0-crtc3     Disabled
- 0x904fe3a92080  711     711     2       gfx_0.0.0       Disabled
- 0x904fe2ce4100  712     712     2       comp_1.0.0      Disabled
- 0x904fe2ce0000  713     713     2       comp_1.1.0      Disabled
- 0x904fe2ce2080  714     714     2       comp_1.2.0      Disabled
- 0x904fd4d12080  715     715     2       comp_1.3.0      Disabled
- 0x904fd4d14100  716     716     2       comp_1.0.1      Disabled
- 0x904fd4d10000  717     717     2       comp_1.1.1      Disabled
- 0x904fd68d0000  718     718     2       comp_1.2.1      Disabled
- 0x904fd68d2080  719     719     2       comp_1.3.1      Disabled
- 0x904fd68d4100  720     720     2       sdma0   Disabled
- 0x90500432c100  721     721     2       vcn_dec_0       Disabled
- 0x905004328000  722     722     2       vcn_enc_0.0     Disabled
- 0x90500432a080  723     723     2       vcn_enc_0.1     Disabled
- 0x9050042f8000  724     724     2       jpeg_dec        Disabled
- 0x904fcba40000  732     732     1       NetworkManager  Disabled
- 0x904ff67e8000  819     819     1       polkitd Disabled
- 0x904fe3e12080  835     835     1       iwd     Disabled
- 0x904fcb1aa080  944     944     1       systemd Disabled
- 0x904fc68e8000  948     948     944     (sd-pam)        Disabled
- 0x904fd1fd2080  961     961     944     gamemoded       Disabled
- 0x904fc1752080  965     965     944     dbus-daemon     Disabled
- 0x904fcbd34100  1067    1067    944     pipewire        Disabled
- 0x904ff66da080  1068    1068    944     wireplumber     Disabled
- 0x904fc4c0a080  1069    1069    1       rtkit-daemon    Disabled
- 0x9050157a4100  1457    1457    944     pipewire-pulse  Disabled
- 0x904fe1b2c100  1474    1474    1       upowerd Disabled
- 0x9050650d4100  1538    1538    1       udisksd Disabled
- 0x90505fa48000  1953    1953    2       tls-strp        Disabled
- 0x905061580000  5031    5031    944     dconf-service   Disabled
- 0x9050be7fc100  7645    7645    1       sshd    Disabled
- 0x905189e02080  10288   10288   1       atomupd-daemon  Disabled
- 0x904fc38b2080  10347   10347   944     kio_http_cache_ Disabled
- 0x9050d1668000  17807   17807   2       kworker/u33:4   Disabled
- 0x905018f28000  36616   36616   1       sddm    Disabled
- 0x9050694a8000  36622   36622   36616   sddm-helper     Disabled
- 0x904fcbd38000  36629   36629   36622   sddm-helper-sta Disabled
- 0x9050be4a8000  36630   36630   36629   Xorg    Disabled
- 0x9050be4aa080  36643   36643   36629   startplasma-x11 Disabled
- 0x9050ce498000  36697   36697   944     baloo_file      Disabled
- 0x9050ce49c100  36701   36701   944     xdg-desktop-por Disabled
- 0x904fcbd30000  36708   36708   944     xdg-document-po Disabled
- 0x904fcb56c100  36712   36712   944     xdg-permission- Disabled
- 0x904fee3b8000  36719   36719   36708   fusermount3     Disabled
- 0x904fcb3d4100  36732   36732   944     ksmserver       Disabled
- 0x904fc1464100  36734   36734   944     kded5   Disabled
- 0x904fc1460000  36735   36735   944     kwin_x11        Disabled
- 0x904fcb66a080  36765   36765   944     plasmashell     Disabled
- 0x904fcb66c100  36766   36766   944     kglobalaccel5   Disabled
- 0x905050d8a080  36801   36801   944     kactivitymanage Disabled
- 0x905050d8c100  36804   36804   944     gmenudbusmenupr Disabled
- 0x904ff67ec100  36805   36805   944     polkit-kde-auth Disabled
- 0x904ff5b5a080  36806   36806   944     org_kde_powerde Disabled
- 0x904ff5b58000  36807   36807   944     xdg-desktop-por Disabled
- 0x904fd1018000  36808   36808   944     xembedsniproxy  Disabled
- 0x904fd448a080  36909   36909   944     kscreen_backend Disabled
- 0x9050a67e0000  36943   36943   944     kdeconnectd     Disabled
- 0x90518077a080  36948   36948   944     agent   Disabled
- 0x9050c3242080  36949   36949   944     ibus-daemon     Disabled
- 0x9050c3244100  36951   36951   944     kaccess Disabled
- 0x9051ad4b8000  36955   36955   944     DiscoverNotifie Disabled
- 0x904fc4c80000  36958   36958   944     bash    Disabled
- 0x904fc327a080  36987   36987   36949   ibus-dconf      Disabled
- 0x9051ac518000  36993   36993   944     kimpanel-ibus-p Disabled
- 0x9050c30a0000  36995   36995   36949   ibus-extension- Disabled
- 0x9050c30a2080  37003   37003   944     ibus-portal     Disabled
- 0x9050a67e2080  37037   37037   944     at-spi-bus-laun Disabled
- 0x90518b854100  37063   37063   37037   dbus-daemon     Disabled
- 0x905189e00000  37072   37072   944     at-spi2-registr Disabled
- 0x90504d4a8000  37084   37084   36949   ibus-engine-sim Disabled
- 0x905065acc100  37224   37224   36958   steam   Disabled
- 0x905069454100  37225   37225   2       kworker/u33:0   Disabled
- 0x90506ad20000  37259   37259   36765   dolphin Disabled
- 0x9050cf2d8000  37272   37272   37224   steam-runtime-s Disabled
- 0x904fcb1a8000  37295   37295   37272   srt-bwrap       Disabled
- 0x904ff6642080  37466   37466   37224   steam-runtime-l Disabled
- 0x904fed4ba080  37540   37540   37295   pressure-vessel Disabled
- 0x904fcb7e2080  37564   37564   37540   steamwebhelper  Disabled
- 0x904fdc69a080  37567   37567   37540   steamwebhelper  Disabled
- 0x904ff58d0000  37571   37571   37564   steamwebhelper  Disabled
- 0x904ff58d4100  37572   37572   37564   steamwebhelper  Disabled
- 0x90504d410000  37618   37618   37564   steamwebhelper  Disabled
- 0x905069452080  37633   37633   37572   steamwebhelper  Disabled
- 0x904ff6934100  37644   37644   37572   steamwebhelper  Disabled
- 0x90507b812080  38010   38010   37564   steamwebhelper  Disabled
- 0x9050c30a4100  66880   66880   2       kworker/0:2     Disabled
- 0x9050cf458000  70999   70999   7645    sshd    Disabled
- 0x904fc32b8000  71009   71009   7645    sshd    Disabled
- 0x9050be4b2080  71013   71013   70999   sshd    Disabled
- 0x905128342080  71027   71027   71013   bash    Disabled
- 0x9051fe5d0000  71044   71044   71009   sshd    Disabled
- 0x904fd1af2080  71058   71058   71044   sftp-server     Disabled
- 0x904fe3a70000  71647   71647   2       kworker/7:1     Disabled
- 0x904fc5a34100  71965   71965   2       kworker/1:0     Disabled
- 0x90518b470000  71966   71966   2       kworker/2:2     Disabled
- 0x90506ad22080  71967   71967   2       kworker/3:1     Disabled
- 0x904fdba82080  71969   71969   2       kworker/5:1     Disabled
- 0x90505f81c100  71971   71971   2       kworker/6:3     Disabled
- 0x904fc69a8000  71977   71977   2       irq/68-mmc0     Disabled
- 0x9051fe492080  72122   72122   1       fwupd   Disabled
- 0x90513b5bc100  72405   72405   1       accounts-daemon Disabled
- 0x90506af10000  72713   72713   37571   steamwebhelper  Disabled
- 0x9051fe52a080  73350   73350   2       kworker/4:2     Disabled
- 0x904ff8540000  73563   73563   2       kworker/2:1     Disabled
- 0x90505fb90000  73576   73576   2       kworker/u32:5   Disabled
- 0x904ff2e42080  73763   73763   2       kworker/6:0     Disabled
- 0x904fc145c100  73815   73815   2       kworker/u32:3   Disabled
- 0x9050be76a080  73844   73844   2       kworker/1:1     Disabled
- 0x904fd1b60000  73878   73878   2       kworker/u32:7   Disabled
- 0x9050ce42c100  73888   73888   944     flatpak-session Disabled
- 0x904fcb860000  73893   73893   944     p11-kit-server  Disabled
- 0x905025e3c100  74565   74565   2       kworker/0:1     Disabled
- 0x904ff8568000  74961   74961   2       kworker/u32:0   Disabled
- 0x90501518c100  74977   74977   2       kworker/3:2     Disabled
- 0x9050ce332080  75589   75589   1       geoclue Disabled
- 0x905084690000  75590   75590   2       kworker/u32:6   Disabled
- 0x9050ce330000  75596   75596   1       wpa_supplicant  Disabled
- 0x904fe90f0000  75597   75597   2       kworker/u32:8   Disabled
- 0x904fc0a4c100  75812   75812   2       kworker/u32:9   Disabled
- 0x9050cf440000  75876   75876   2       kworker/7:0     Disabled
- 0x9050138c8000  75901   75901   37572   steamwebhelper  Disabled
- 0x9051adcc2080  75939   75939   37224   reaper  Disabled
- 0x9051adcc4100  75940   75940   75939   srt-bwrap       Disabled
- 0x904ff2fc0000  76014   76014   75940   pressure-vessel Disabled
- 0x9051acfa2080  76038   76038   76014   aces    Disabled
- 0x9051add62080  76097   76097   37224   gameoverlayui   Disabled
- 0x904fe3ed8000  76101   76101   37572   steamwebhelper  Disabled
- 0x904fe3eda080  76224   76224   2       kworker/5:2     Disabled
- 0x9050cf45a080  76232   76232   2       kworker/u32:1   Disabled
- 0x904fcb668000  76233   76233   2       kworker/4:1     Disabled
- 0x90505fb92080  76244   76244   2       kworker/2:0     Disabled
- 0x905025e38000  76378   76378   71027   sudo    Disabled
- 0x904ff8544100  76382   76382   76378   insmod  Disabled
- 0x9050d13f2080  76384   76384   2       kworker/u32:2   Disabled
- `

**My questions are:**
What are the processes that are related to the games? 
What processes relate to the chat between friends on the device and friends on the games?  
What are the processes that are related to the Firefox browser? 
What are the processes that are related to proton?

Thank you 
Ruba

**Comment by ikelos** [comment] 2024-04-24 06:38
Hi there, thanks very much for your question, but this doesn't seem to be an issue with Volatility?  The GitHub issue tracker is to help us keep track of and resolve issues with Volatility and is not a general forum for people to ask their personal research questions.

If you would like to ask the community for support, please use our public slack server to do so.  I'll be closing this off as not a bug now...

**Closed as not planned** 2024-04-24 06:38 UTC
