### ISSUE TITLE
NetScan \ Sockets \ ConnScan

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#302] opened 2020-08-17 15:41 UTC
**Is your feature request related to a problem? Please describe.**
The need to investigate network connections.

**Describe the solution you'd like**
NetScan \ Sockets \ CommScan like in volatility2

**Describe alternatives you've considered**
Scanning for connections with process attribution.

**Comment by ikelos** [comment] 2020-08-17 15:57
This looks like a duplicate of #129, please reopen this if you feel the bug doesn't cover it entirely, and we'll try to make this more accurate.  You can follow along with the progress of netscan at #226 ...

**Closed by ikelos** 2020-08-17 15:57 UTC

**Comment by AsafEitani** [comment] 2020-08-18 06:47
Sorry - I must of missed that. Thanks! looks awesome, can't wait for it to merge 5:)
