### ISSUE TITLE
Mismatch in procdump md5 checksums between vol2 and vol3

### ISSUE THREAD

**Issue by zin-htet-aung** [volatilityfoundation/volatility3#437] opened 2021-01-28 10:24 UTC
**Describe the bug**
When I make procdump with volatility3 and calculate a md5checksum of it, its md5checksum is different with procdump that with volatility 2.
I mean same process ,get files but different checksum
**Context**
Volatility Version:  3
Operating System:  linux
Python Version:  3.9.1

**Comment by ikelos** [comment] 2021-01-28 10:41
Hi there, I think this is a duplicate of #160?  In short, volatility 3 should use the same method as volatility 2 when run with --memory.  I'm going to mark this as closed, but if you think this doesn't quite fit with #160, please feel free to reopen this...  5:)

**Closed as completed by ikelos** 2021-01-28 10:41 UTC

**Comment by zin-htet-aung** [comment] 2021-01-28 11:39
Yes, It is same with #160. How can we get same checksum? Can you write full command for this?
python vol.py -f a.raw .......................
And I hope to get like this link for volatility 3 for newbies ```https://github.com/volatilityfoundation/volatility/wiki/Command-Reference ```. That's too useful for newbies.

**Comment by ikelos** [comment] 2021-01-28 12:49
Hiya, you'd need to rerun volatility 2 against the memory images, with the following
```
python2 vol.py procdump -f /path/to/file --memory --dump-dir /path/to/dump/dir
```
At the moment, there simply isn't the code to produce the same output as there is for volatility 2, so if you can't recreate the dumps with volatility 2, you'll have to wait for some code to be written that carry out the same thing.  At the moment, that's not a priority for volatility 3, but you or some member of the community may find it useful to add the feature.

As for the quick reference, there isn't yet anything like this available, although the following page may cover listing the available plugins.  https://volatility3.readthedocs.io/en/latest/volatility.plugins.html

I'd suggest filing a separate issue making the request for that kind of documentation, so that we can keep track of it and ensure it doesn't get forgotten...
