### ISSUE TITLE
windows.driverscan doesn't generate any data for win-xp samples

### ISSUE THREAD

**Issue by mtressler** [volatilityfoundation/volatility3#425] opened 2021-01-13 20:21 UTC
Describe the bug
When the plugin windows.driverscan is run on an win-xp sample it runs without error but no data is output.

Context
Volatility Version: release/v2.0.0
Operating System: Windows/WSL
Python Version: 3.8.2
Suspected Operating System: win-xp
Command: 
python3 vol.py -f samples/win-xp-laptop-2005-07-04-1430.img windows.driverscan
python3 vol.py -f samples/win-xp-laptop-2005-06-25.img windows.driverscan

To Reproduce
Run driverscan plugin on win-xp sample

Expected behavior
Should output all drivers present in the sample

win-xp-laptop-2005-07-04-1430.img version: 15.2600
win-xp-laptop-2005-06-25.img          version: 15.2600

**Comment by ikelos** [comment] 2021-01-13 20:31
So this one looks like the type test is failing a lot of entries, but providing `skip_type_test = True` just returns garbage (interpreted as unicode), so I'm not sure what's going wrong here, but probably one for @iMHLv2 to investigate I'm afraid...

**Comment by iMHLv2** [comment] 2021-09-15 15:21
This is a duplicate of https://github.com/volatilityfoundation/volatility3/issues/529 which has a patch and MR waiting, so I'm going to close this ticket.

**Closed as completed by iMHLv2** 2021-09-15 15:21 UTC
