### ISSUE TITLE
No module named 'volatility3.cli'

### ISSUE THREAD

**Issue by ShutdownRepo** [volatilityfoundation/volatility3#1002] opened 2023-09-05 15:39 UTC
# Describe the bug
`ModuleNotFoundError` error raised when trying to run volatility after a fresh install

# To Reproduce
Error is raised after install with either of the following methods

```bash
python3 -m pipx install git+https://github.com/volatilityfoundation/volatility3
vol --help
```

or

```bash
git -C /opt/tools clone https://github.com/volatilityfoundation/volatility3.git
python3 -m pipx install /opt/tools/volatility3
vol --help
```

# Example error output
```
Traceback (most recent call last):
  File "/root/.local/bin/vol", line 5, in <module>
    from volatility3.cli import main
ModuleNotFoundError: No module named 'volatility3.cli'
```

**Comment by ShutdownRepo** [comment] 2023-09-05 15:46
I think it was introduced in b4c6b661f01fc3dde54362a4f55be4d89e4cc6e5
This install would work
```bash
git -C /opt/tools/ clone https://github.com/volatilityfoundation/volatility3
git -C /opt/tools/volatility3 revert b4c6b661f01fc3dde54362a4f55be4d89e4cc6e5
python3 -m pipx install /opt/tools/volatility3
vol --help
```

**Comment by ikelos** [comment] 2023-09-05 17:25
Thanks very much for letting us know.  Could you please test the proposed fix in #1003 and let us know if it resolves the problem?

**Comment by qu35t-code** [comment] 2023-09-05 18:38
Hey, fix on issues/issue1002 doesn't works

```bash
> git checkout issues/issue1002

Branch 'issues/issue1002' set up to track remote branch 'issues/issue1002' from 'origin'.
Switched to a new branch 'issues/issue1002'

> python3 -m pipx install .
  installed package volatility3 2.5.0, installed using Python 3.9.2
  These apps are now globally available
    - vol
    - volshell
done! ✨ 🌟 ✨

> vol --help
Traceback (most recent call last):
  File "/root/.local/bin/vol", line 5, in <module>
    from volatility3.cli import main
ModuleNotFoundError: No module named 'volatility3.cli'
```


If we revert to this commit it works : b4c6b661f01fc3dde54362a4f55be4d89e4cc6e5

```bash
> git -C /opt/tools/volatility3 revert b4c6b661f01fc3dde54362a4f55be4d89e4cc6e5
[develop 5458cef0] Revert "Core: Include only volatility3 in distributions packages"
 1 file changed, 1 insertion(+), 1 deletion(-)

> python3 -m pipx uninstall volatility3
Nothing to uninstall for volatility3 😴

> python3 -m pipx install .
  installed package volatility3 2.5.0, installed using Python 3.9.2
  These apps are now globally available
    - vol
    - volshell
done! ✨ 🌟 ✨

> vol --help
Volatility 3 Framework 2.5.0
usage: volatility [-h] [-c CONFIG] [--parallelism [{processes,threads,off}]] [-e EXTEND] [-p PLUGIN_DIRS] [-s SYMBOL_DIRS]
                  [-v] [-l LOG] [-o OUTPUT_DIR] [-q] [-r RENDERER] [-f FILE] [--write-config] [--save-config SAVE_CONFIG]
                  [--clear-cache] [--cache-path CACHE_PATH] [--offline] [--single-location SINGLE_LOCATION]
                  [--stackers [STACKERS ...]] [--single-swap-locations [SINGLE_SWAP_LOCATIONS ...]]
                  plugin ...
```

**Comment by ikelos** [comment] 2023-09-05 20:36
I'm afraid I can't recreate your situation.  On the `issues/issue1002` branch I get the following:

```
ikelos volatility3 # python -m pipx install .           
  installed package volatility3 2.5.0, installed using Python 3.11.5
  These apps are now globally available
    - vol
    - volshell
⚠️  Note: '/root/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your PATH is updated. Run `pipx ensurepath` to automatically add
    it, or manually modify your PATH in your shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨
ikelos volatility3 # /root/.local/bin/vol --help
Volatility 3 Framework 2.5.0
usage: volatility [-h] [-c CONFIG] [--parallelism [{processes,threads,off}]] [-e EXTEND] [-p PLUGIN_DIRS] [-s SYMBOL_DIRS] [-v] [-l LOG] [-o OUTPUT_DIR] [-q] [-r RENDERER] [-f FILE]
                  [--write-config] [--save-config SAVE_CONFIG] [--clear-cache] [--cache-path CACHE_PATH] [--offline] [--single-location SINGLE_LOCATION] [--stackers [STACKERS ...]]
                  [--single-swap-locations [SINGLE_SWAP_LOCATIONS ...]]
                  plugin ...

An open-source memory forensics framework

options:
  -h, --help            Show this help message and exit, for specific plugin options use 'volatility <pluginname> --help'
  ```
  
  Are you sure it isn't using a cached copy in some way?

**Comment by ShutdownRepo** [comment] 2023-09-05 21:41
Nope, you can test with the following dockerfile
```dockerfile
FROM debian:11-slim
RUN apt-get update && apt-get install -y python3-pip git
RUN git clone https://github.com/volatilityfoundation/volatility3/ -b issues/issue1002
RUN cd volatility3 && pip3 install .
```
```bash
docker build --no-cache -t voltest . && docker run --rm --tty --interactive voltest
```
```
$ vol --help
root@d64b249b79f9:/# vol --help
Traceback (most recent call last):
  File "/usr/local/bin/vol", line 5, in <module>
    from volatility3.cli import main
ModuleNotFoundError: No module named 'volatility3'
```

**Comment by ikelos** [comment] 2023-09-05 22:10
I have reverted the original commit.  The changes I made installed the directories under `volatility3` into `dist-files`, rather than under a `volatility3` directory that was under `dist-files`.  I haven't found a way to cleanly tell setup.py that I *only* want files under the `volatility3` directory for the wheel/package, but that the source should still include `doc` and things like that.  If anyone has more experience with `setup.py` do feel free to chime in...

**Comment by ikelos** [comment] 2023-09-05 22:11
Also, thank you for reporting this and having patience with me.  I think I was running vol from the volatility directory when I did my tests, so it was picking up the local directory, rather than the installed package.  Sorry for the inconvenience, I think I need some sleep...  5:S

**Comment by ShutdownRepo** [comment] 2023-09-05 22:12
Thank you 🙏

**Comment by ikelos** [comment] 2023-09-05 22:52
Ok, I've updated #1003 , if you'd be able to test it again, it seems to successfully work on your docker image and hopefully keeps all our other packages as intended.  If it works I'll get it merged...  5:)

**Comment by ShutdownRepo** [comment] 2023-09-05 23:09
I can confirm

**Closed as completed** 2023-09-05 23:54 UTC
Labels: awaiting-user-verification
