### ISSUE TITLE
windows.mutantscan generates too few mutexes for win10-x86 samples

### ISSUE THREAD

**Issue by mtressler** [volatilityfoundation/volatility3#424] opened 2021-01-13 20:09 UTC
Describe the bug
When the plugin windows.netscan is run on an x86 sample it runs without error but only four mutexes are found. Based on my convo with MHL he believes that is too few and probably indicates an issue.

Context
Volatility Version: release/v2.0.0
Operating System: Windows/WSL
Python Version: 3.8.2
Suspected Operating System: win10-x86
Command: python3 vol.py -f samples/win10-x86-2016-07-08.lime windows.mutantscan

To Reproduce
Run mutantscan plugin on x86 sample

Expected behavior
Should output all mutexes in the sample

**Comment by ikelos** [comment] 2021-01-13 20:17
Hmmmm,

Based only on the filename, I get the following output (although it takes a long time)...

```
mike@ikelos /home/mike/volatility3 (develop*) $ python vol.py -f win10-x86-2016-07-08.lime windows.mutantscan
Volatility 3 Framework 2.0.0
Progress:  100.00		PDB scanning finished                     
Offset	Name

0x85256958	BcdSyncMutant
0x85e56958	BcdSyncMutant
0x9cb21c48	N/A
0xa723f480	MSCTF.Asm.MutexDefault2S-1-5-21-3902365657-1410629153-1893644554-500
```

I'm not saying that there isn't anything to look into (that's not a lot of mutexes), but the report says that no data is output, and I wanted to verify if we're seeing different results?  It might be that Microsoft has tampered with the symbol files (we've seen that before, where the PDBs are republished without the necessary types, but then I would expect it to error out if that were the case)...

**Comment by mtressler** [comment] 2021-01-13 20:25
Oh yea sorry, I also get those four but MHL said that is far too few and probably indicates a bug.

**Comment by mtressler** [comment] 2021-01-13 20:26
I've updated the bug info

**Comment by ikelos** [comment] 2021-01-13 20:27
Hehehe, sure, just wanted to check we were seeing the same thing.  5;)

**Comment by ikelos** [comment] 2021-01-14 09:17
I think @iMHLv2 may have resolved this, could you please verify on either `release/2.0.0` or `develop` (they both have the fix)?

**Comment by mtressler** [comment] 2021-01-14 17:06
No, the PR #426 was a fix for a different issue if that was what you were referring to. I'm still only getting those four mutexes. Would it be worth it to run mutantscan on this sample in vol2 to see what the output should be? I tried but it was throwing an error before it output any data.

**Comment by iMHLv2** [comment] 2021-09-15 15:23
This is a duplicate of https://github.com/volatilityfoundation/volatility3/issues/530 which has a fix and MR waiting, so I'm going to close this ticket.

**Closed as completed by iMHLv2** 2021-09-15 15:23 UTC
