### ISSUE TITLE
Hbootkey is not valid

### ISSUE THREAD

**Issue by 12089897411** [volatilityfoundation/volatility3#812] opened 2022-08-20 02:35 UTC
**Describe the bug**

**Context**
Volatility Version:   volatility3
Operating System:  Win10x64_19043
Python Version:  3.9
Suspected Operating System:  Win10x64_19043
Command:  python vol.py -f 20220820.mem windows.hashdump

**To Reproduce**

1. Use command 'python vol.py -f 20220820.mem windows.hashdump'
2. See error  'WARNING  volatility3.plugins.windows.hashdump: Hbootkey is not valid'

**Screenshots**
![1](https://user-images.githubusercontent.com/108512675/185725779-605c5739-1867-4fb0-af8c-a6ea717d699e.png)
![2](https://user-images.githubusercontent.com/108512675/185725786-78388497-de94-4eff-9cbc-3fdad93789d2.PNG)

**Additional information**
Add any other information about the problem here.

**Comment by digitalisx** [comment] 2022-08-20 07:09
Hello, @12089897411
Could you provide logs and dumps to help us understand what is causing it?

```shell
> python3 vol.py -f case.mem -vvvv windows.hashdump
```

Duplicate of 
- #617

**Comment by 12089897411** [comment] 2022-08-20 10:46
Hi@digitalisx 

I shared the file on the Dropbox. The link is as follows:
https://www.dropbox.com/s/cuhn860amsc8vrm/20220820.mem?dl=0

thanks

**Comment by digitalisx** [comment] 2022-08-20 16:43
Hello, @12089897411
Thank you for providing data and information.
I'll track down the cause of this as soon as time permits. :)

**Comment by ikelos** [comment] 2022-08-21 20:54
It's possible that the registry entry used by hashdump isn't present in the memory.  This tends to suggest a smeared memory image, or something strange going on with the in-memory registry.  I'm afraid there's unlikely to be much we can do to improve the situation.

**Comment by 12089897411** [comment] 2022-08-22 02:38
Hi @ikelos 

That's ok！If I want to get users from Mac or Linux dumps,which command shoud I use?

thanks

**Comment by ikelos** [comment] 2022-08-22 07:53
Hi this question isn't really a bug, so it might be better to ask it on our [slack channels](https://www.volatilityfoundation.org/slack) where you could get a more interactive response.  I'm not sure we have any plugins specifically for enumerating users on either linux or mac I'm afraid.   You might find some luck just outputting the memory and using grep to search for the passwd file, in case it's cached in memory by PAM or similar?

I'm going to mark this as closed since the message isn't really a bug, but expected operation when volatility can't find necessary information within an image.  Please feel free to reopen it if you feel there's still an issue...

**Closed as completed by ikelos** 2022-08-22 07:53 UTC
