### ISSUE TITLE
Help with renderer exception

### ISSUE THREAD

**Issue by dadokkio** [volatilityfoundation/volatility3#219] opened 2020-05-21 06:54 UTC
I'm not sure this is an issue, but probably is just asking help to understand how to manage properly data.

I and @garanews are trying to run some volatility plugins with dask and obtain from any of them a json with the rendered output. 
To do so we've created a custom rendered 99% inspired from cli.text_renderer.JsonRenderer that instead of writing to sysout returns the generated dict.

If the plugin runs without error everything is ok and a properly formatted json is returned, while if an error happens an Exception is returned and all the output is lost.

This is the actual renderer:

```
class ReturnJsonRenderer(JsonRenderer):
    def render(self, grid: interfaces.renderers.TreeGrid):
        final_output = ({}, [])

        def visitor(
            node: Optional[interfaces.renderers.TreeNode],
            accumulator: Tuple[Dict[str, Dict[str, Any]], List[Dict[str, Any]]],
        ) -> Tuple[Dict[str, Dict[str, Any]], List[Dict[str, Any]]]:
            # Nodes always have a path value, giving them a path_depth of at least 1, we use max just in case
            acc_map, final_tree = accumulator
            node_dict = {"__children": []}
            for column_index in range(len(grid.columns)):
                column = grid.columns[column_index]
                renderer = self._type_renderers.get(
                    column.type, self._type_renderers["default"]
                )
                data = renderer(list(node.values)[column_index])
                if isinstance(data, interfaces.renderers.BaseAbsentValue):
                    data = None
                node_dict[column.name] = data
            if node.parent:
                acc_map[node.parent.path]["__children"].append(node_dict)
            else:
                final_tree.append(node_dict)
            acc_map[node.path] = node_dict
            return (acc_map, final_tree)

        if not grid.populated:
            grid.populate(visitor, final_output)
        else:
            grid.visit(node=None, function=visitor, initial_accumulator=final_output)
        return final_output[1]
```

And the code that is using it is:

```
    try:
        constructed = plugins.construct_plugin(
            ctx, automagics, plugin, base_config_path, None, None
        )
        run_plugin = constructed.run()
        result = json_renderer().render(run_plugin)
    except exceptions.UnsatisfiedException as excp:
        return False
    except Exception as excp:
        return False
```

A sample error is like this one:

```
(vol_test) dadokkio@PensieroProfondo:~/Desktop/MM$ python main.py 
distributed.worker - WARNING -  Compute Failed
Function:  run_plugin
args:      ('windows.pslist.PsList', 'nobello.mem', UUID('7c956995-9b2c-11ea-82f0-afefbf11b306'))
kwargs:    {}
Exception: Exception('Page Fault at entry 0x50c9063 in table page table')

Traceback (most recent call last):
[...]
  File "main.py", line 107, in run_plugin
    result = json_renderer().render(run_plugin)
  File "main.py", line 57, in render
    grid.populate(visitor, final_output)
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/renderers/__init__.py", line 196, in populate
    for (level, item) in self._generator:
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/plugins/windows/pslist.py", line 137, in _generator
    yield (0, (proc.UniqueProcessId, proc.InheritedFromUniqueProcessId,
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/objects/__init__.py", line 707, in __getattr__
    member = template(context = self._context, object_info = object_info)
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/objects/templates.py", line 72, in __call__
    return self.vol.object_class(context = context, object_info = object_info, **arguments)
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/objects/__init__.py", line 120, in __new__
    value = cls._unmarshall(context, data_format, object_info)
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/objects/__init__.py", line 304, in _unmarshall
    data = context.layers.read(object_info.layer_name, object_info.offset, length)
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/interfaces/layers.py", line 535, in read
    return self[layer].read(offset, length, pad)
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/layers/linear.py", line 38, in read
    for (offset, _, mapped_offset, mapped_length, layer) in self.mapping(offset, length, ignore_errors = pad):
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/layers/intel.py", line 195, in mapping
    chunk_offset, page_size, layer_name = self._translate(offset)
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/layers/intel.py", line 315, in _translate
    return self._translate_swap(self, offset, self._bits_per_register // 2)
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/layers/intel.py", line 273, in _translate_swap
    return super()._translate(offset)
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/layers/intel.py", line 99, in _translate
    entry, position = self._translate_entry(offset)
  File "/home/dadokkio/miniconda3/envs/vol_test/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/layers/intel.py", line 141, in _translate_entry
    raise exceptions.PagedInvalidAddressException(self.name, offset, position + 1, entry,
Exception: Page Fault at entry 0x50c9063 in table page table
```

The error is generated in the .render() function but I'm not able to catch the exception in any way.
I tried to put a try catch in the visitor function and also to create a new class derived from TreeNode to add a try catch in the populate function, but even in this point don't seems to be correct.

There is a way to "render" just the correct part of the plugin result or some suggestion how to obtain partial results and errors together? It's this approach correct or there is a better way to obtain similar results?

**Comment by ikelos** [comment] 2020-05-25 21:22
Sorry not have replied sooner.  Yeah, I need to think through carefully how this will work.  I suspect I need to add an additional option to the renderer to allow for errors to occur, I'm just not sure how best to represent them yet.  I'll try and mock something up over the next week and see how it looks...

**Comment by ikelos** [comment] 2020-05-25 23:18
Hi there, could you please have a try of the `allow-errors-during-population` branch and provide the `populate` function with a `fail_on_errors` variable set to `False`.  The method should then return you an exception if the `Treegrid` did not successfully complete or None if it completes.

**Comment by dadokkio** [comment] 2020-05-26 06:43
With the same code I'm now getting an error:
```
  File "test_new.py", line 56, in render
    grid.populate(visitor, final_output, fail_on_errors=False)
  File "/home/dadokkio/miniconda3/envs/orochi/lib/python3.8/site-packages/volatility-1.0.0b1-py3.8.egg/volatility/framework/renderers/__init__.py", line 218, in populate
    if self._fail_on_errors:
AttributeError: 'TreeGrid' object has no attribute '_fail_on_errors'
```

I need to change something in my renderer class?

**Comment by ikelos** [comment] 2020-05-26 08:29
Nope, sorry, that was entirely my bad.  I'd originally made the code to be a class level variable, and then realized that would be difficult to apply since the class is constructed by the plugins, so converted it, but missed one of the class instances, sorry!  5:S  I've pushed a fix, so it should work as intended now...

**Comment by ikelos** [comment] 2020-06-03 10:10
So, any news on how that branch worked out?  Did it help the situation?  I'll merge it into master if it seemed to do what you'd hoped for?

**Comment by dadokkio** [comment] 2020-06-04 16:59
Hi, sorry for the delay.
I have now some plugins that returns both records and error so now everything is ok.
Unfortunately the image I'm working with is 18gb so it's very difficult to parallelize and debug.

Thanks.

**Comment by ikelos** [comment] 2020-06-04 18:33
Sure, and I'm sorry that the modest parallelization we've included probably doesn't help that much either.  We do hope to improve the parallelization at some point, but it's really tricky ensure that everybody's plugins play nicely with it...  5:S

I'm going to close this issue as resolved if that's ok?  If you still feel there's an unresolved issue do please reopen it and let us know...  5:)

**Closed by ikelos** 2020-06-04 18:33 UTC
