### ISSUE TITLE
Symbol table requirement was not fulfilled even though I created a symbol with an appropriate Kernel package and debug info package.

### ISSUE THREAD

**Issue by Linux-mem-forensics** [volatilityfoundation/volatility3#703] opened 2022-04-17 02:53 UTC
Hello All, I hope you are well.

I am trying to run Volatility 3 on Ubuntu 18.04.6 memory image (captured using AVLM) on a Windows 10 machine. I created symbol tables (Vmlinux5.4.0-84-generic and System.map-5.4.0-84-generic) using Dwarf2json. Ran "banner" just to check the version, its the same (Linux version 5.4.0-84-generic).

I am still getting the following errors:

   Unsatisfied requirement plugins.PsTree.primary: Memory layer for the kernel
   Unsatisfied requirement plugins.PsTree.vmlinux: Linux kernel symbols

   A symbol table requirement was not fulfilled.  Please verify that:
   A translation layer requirement was not fulfilled.  Please verify that:
   
 Can anyone please suggest what I could be doing wrong or what should I do to make it work.
 
 Thank you.

**Comment by ikelos** [comment] 2022-04-17 06:05
Hiya, please check the output from the following plugins `banners` and `isfinfo`.  You need to use the exact same version of the banner (`5.4.0-84-generic` alone is not enough, it needs to be an _identical_ banner string).  This is because linux allows different compilation options that can change the size of structures and thus might break volatility.  The second thing to check is that volatility can actually see the symbol file, for a linux JSON file, it currently needs to live in a symbols folder under a `linux` directory (even if you're providing the directory using `-s`).  If it's in the wrong directory, it won't be used.  You can verify that it's been found and which directory it's under using `isfinfo`.  We've got a pull request in to change this (#630), but it's still under review at the moment.

Also, when filling in issues, please include the output of running a plugin using `-vvv` so that we can see the verbose output to better diagnose the problem...

**Comment by Linux-mem-forensics** [comment] 2022-04-17 14:54
This is what I get when I ran the Banner plugin, can you please elaborate on the naming of the JSON symbol file? I have named it as Vmlinux5.4.0-84-generic.json and placed it under the /Vol3/symbols/linux.

It can see the JSON file when ran the ISFINFO plugin.
"volatility3-1.0.0/volatility3/symbols/linux/vmlinux-5.4.0-84-generic.json    Unknown 18  10108       172893  1727    -       Linux version 5.4.0-84-generic (buildd@lgw01-amd64-050) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 (Ubuntu 5.4.0-84.94-generic 5.4.133)"

Banner plugin output - 

INFO     root        : Volatility plugins path: ['volatility3-1.0.0\\volatility3\\plugins', 'volatility3-1.0.0\\volatility3\\framework\\plugins']
INFO     root        : Volatility symbols path: _NamespacePath(['volatility3-1.0.0\\volatility3\\symbols'])
INFO     volatility3.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: No module named 'yara'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.yarascan based on file: yarascan
DEBUG    volatility3.framework: No module named 'Crypto'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.cachedump based on file: windows\cachedump
INFO     volatility3.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: No module named 'yara'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.callbacks based on file: windows\callbacks
DEBUG    volatility3.framework: No module named 'Crypto'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.hashdump based on file: windows\hashdump
DEBUG    volatility3.framework: No module named 'Crypto'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.lsadump based on file: windows\lsadump
INFO     volatility3.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: No module named 'yara'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.svcscan based on file: windows\svcscan
INFO     volatility3.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility3.framework: No module named 'yara'
DEBUG    volatility3.framework: Failed to import module volatility3.plugins.windows.vadyarascan based on file: windows\vadyarascan
INFO     root        : The following plugins could not be loaded (use -vv to see why): volatility3.plugins.windows.cachedump, volatility3.plugins.windows.callbacks, volatility3.plugins.windows.hashdump, volatility3.plugins.windows.lsadump, volatility3.plugins.windows.svcscan, volatility3.plugins.windows.vadyarascan, volatility3.plugins.yarascan
INFO     volatility3.framework.automagic: No plugin category detected
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Banners.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Banners.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Banners.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Banners.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Banners
INFO     volatility3.framework.automagic: Running automagic: SymbolBannerCache
INFO     volatility3.framework.automagic: Running automagic: MacBannerCache
INFO     volatility3.framework.automagic: Running automagic: LinuxBannerCache
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Banners.primary
DEBUG    volatility3.framework.automagic.windows: Self-referential pointer not in well-known location, moving to recent windows heuristic
INFO     volatility3.framework.automagic.mac: No Mac banners found - if this is a mac plugin, please check your symbol files location
DEBUG    volatility3.framework.automagic.linux: No suitable linux banner could be matched
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Banners.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Banners.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Banners.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Banners.primary.base_layer
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['LimeLayer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: WintelHelper
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
INFO     volatility3.framework.automagic: Running automagic: MacSymbolFinder
INFO     volatility3.framework.automagic: Running automagic: LinuxSymbolFinder

Offset  Banner

0x50a001a0      Linux version 5.4.0-84-generic (buildd@lcy01-amd64-007) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #94~18.04.1-Ubuntu SMP Thu Aug 26 23:17:46 UTC 2021 (Ubuntu 5.4.0-84.94~18.04.1-generic 5.4.133)
0x51591d94      Linux version 5.4.0-84-generic (buildd@lcy01-amd64-007) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #94~18.04.1-Ubuntu SMP Thu Aug 26 23:17:46 UTC 2021 (Ubuntu 5.4.0-84.94~18.04.1-generic 5.4.133)
0x588551e0      Linux version 5.4.0-84-generic (buildd@lcy01-amd64-007) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #94~18.04.1-Ubuntu SMP Thu Aug 26 23:17:46 UTC 2021 (Ubuntu 5.4.0-84.94~18.04.1-generic 5.4.133)
0x7bd00010      Linux version 5.4.0-84-generic (buildd@lcy01-amd64-007) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #94~18.04.1-Ubuntu SMP Thu Aug 26 23:17:46 UTC 2021 (Ubuntu 5.4.0-84.94~18.04.1-generic 5.4.133)

Thank you very much for the help!

**Comment by ikelos** [comment] 2022-04-17 15:06
Thanks for that information, the ISF path is fine, since `isfinfo` detected it.  The issue is that the JSON file is for:
```Linux version 5.4.0-84-generic (buildd@lgw01-amd64-050) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #94-Ubuntu SMP Thu Aug 26 20:27:37 UTC 2021 (Ubuntu 5.4.0-84.94-generic 5.4.133)```
and the banner is for:
```Linux version 5.4.0-84-generic (buildd@lcy01-amd64-007) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu118.04)) #9418.04.1-Ubuntu SMP Thu Aug 26 23:17:46 UTC 2021 (Ubuntu 5.4.0-84.9418.04.1-generic 5.4.133)```
These were compiled with different versions of gcc and for different versions of Ubuntu (20 vs 18).  You're doing all the right things, but you've got the wrong kernel file to work from.  You must find one that matches the banner *exactly* from your image.

I don't think this is an issue with volatility, so I'm going to close this off.  If you'd like more direct support, please go to https://www.volatilityfoundation.org/slack where you're more likely to get interactive support with problems...  5:)

**Closed as completed by ikelos** 2022-04-17 15:06 UTC

**Comment by Linux-mem-forensics** [comment] 2022-04-17 15:10
Understood, thank you for the information.
